(ns cljs.midi-standard)

(def control-change-names
  {0   "Bank Select (MSB)"
   1   "Modulation Wheel"
   2   "Breath controller"
   4   "Foot Pedal (MSB)"
   5   "Portamento Time (MSB)"
   6   "Data Entry (MSB) - cc100=0 & cc101=0 is pitch bend range"
   7   "Volume (MSB)"
   8   "Balance (MSB)"
   9   "Undefined CC"
   10  "Pan position (MSB)"
   11  "Expression (MSB)"
   12  "Effect Control 1 (MSB)"
   13  "Effect Control 2 (MSB)"
   16  "Ribbon Controller or General Purpose Slider  1"
   17  "Knob 1 or General Purpose Slider  2"
   18  "General Purpose Slider  3"
   19  "Knob 2 General Purpose   Slider 4"
   20  "Knob 3 or Undefined"
   21  "Knob 4 or Undefined"
   32  "Bank Select (LSB)"
   33  "Modulation Wheel (LSB)"
   34  "Breath controller (LSB)"
   36  "Foot Pedal (LSB)"
   37  "Portamento Time (LSB)"
   38  "Data Entry (LSB)"
   39  "Volume (LSB)"
   40  "Balance (LSB)"
   42  "Pan position (LSB)"
   43  "Expression (LSB)"
   44  "Effect Control 1 (LSB) "
   45  "Effect Control 2 (LSB)"
   64  "Hold/Sustain Pedal (on/off) "
   65  "Portamento (on/off)"
   66  "Sustenuto Pedal (on/off)"
   67  "Soft Pedal (on/off)"
   68  "Legato Pedal (on/off)"
   69  "Hold 2 Pedal (on/off)"
   70  "Sound Variation"
   71  "Resonance (Timbre)"
   72  "Sound Release Time"
   73  "Sound Attack Time"
   74  "Frequency Cutoff"
   75  "Sound Control 6"
   76  "Sound Control 7"
   77  "Sound Control 8"
   78  "Sound Control 9"
   79  "Sound Control 10"
   80  "Decay or General Purpose Button 1 (on/off)"
   81  "Hi Pass Filter Frequency or General Purpose Button 2 (on/off) "
   82  "General Purpose Button 3 (on/off)"
   83  "General Purpose Button 4 (on/off)"
   91  "Reverb Level"
   92  "Tremolo Level"
   93  "Chorus Level"
   94  "Celeste Level or Detune"
   95  "Phaser Level"
   96  "Data Button increment"
   97  "Data Button decrement"
   98  "Non-registered Parameter (LSB)"
   99  "Non-registered Parameter (MSB)"
   100 "Registered Parameter (LSB)"
   101 "Registered Parameter (MSB)"
   120 "All Sound Off"
   121 "All Controllers Off"
   122 "Local Keyboard (on/off)"
   123 "All Notes Off"
   124 "Omni Mode Off"
   125 "Omni Mode On"
   126 "Mono Operation"
   127 "Poly Operation"}
  )

(def program-change-names
  {0   "Acoustic Grand Piano"
   1   "Bright Acoustic Piano"
   2   "Electric Grand Piano"
   3   "Honky-tonk Piano"
   4   "Electric Piano 1"
   5   "Electric Piano 2"
   6   "Harpsichord"
   7   "Clavinet"
   8   "Celesta"
   9   "Glockenspiel"
   10  "Music Box"
   11  "Vibraphone"
   12  "Marimba"
   13  "Xylophone"
   14  "Tubular Bells"
   15  "Dulcimer"
   16  "Drawbar Organ"
   17  "Percussive Organ"
   18  "Rock Organ"
   19  "Church Organ"
   20  "Reed Organ"
   21  "Accordion"
   22  "Harmonica"
   24  "Acoustic Guitar (nylon)"
   25  "Acoustic Guitar (steel)"
   26  "Electric Guitar (jazz)"
   27  "Electric Guitar (clean)"
   28  "Electric Guitar (muted)"
   29  "Overdriven Guitar"
   30  "Distortion Guitar"
   31  "Guitar Harmonics"
   32  "Acoustic Bass"
   33  "Electric Bass (finger)"
   34  "Electric Bass (pick)"
   35  "Fretless Bass"
   36  "Slap Bass 1"
   37  "Slap Bass 2"
   38  "Synth Bass 1"
   39  "Synth Bass 2"
   40  "Violin"
   41  "Viola"
   42  "Cello"
   43  "Contrabass"
   44  "Tremolo Strings"
   45  "Pizzicato Strings"
   46  "Orchestral Harp"
   47  "Timpani"
   48  "String Ensemble 1"
   49  "String Ensemble 2"
   50  "Synth Strings 1"
   51  "Synth Strings 2"
   52  "Choir Aahs"
   53  "Voice Oohs"
   54  "Synth Choir"
   55  "Orchestra Hit"
   56  "Trumpet"
   57  "Trombone"
   58  "Tuba"
   59  "Muted Trumpet"
   60  "French Horn"
   61  "Brass Section"
   62  "Synth Brass 1"
   63  "Synth Brass 2"
   64  "Soprano Sax"
   65  "Alto Sax"
   66  "Tenor Sax"
   67  "Baritone Sax"
   68  "Oboe"
   69  "English Horn"
   70  "Bassoon"
   71  "Clarinet"
   72  "Piccolo"
   73  "Flute"
   74  "Recorder"
   75  "Pan Flute"
   76  "Blown bottle"
   77  "Shakuhachi"
   78  "Whistle"
   79  "Ocarina"
   80  "Lead 1 (square)"
   81  "Lead 2 (sawtooth)"
   82  "Lead 3 (calliope)"
   83  "Lead 4 (chiff)"
   84  "Lead 5 (charang)"
   85  "Lead 6 (voice)"
   86  "Lead 7 (fifths)"
   87  "Lead 8 (bass + lead)"
   88  "Pad 1 (new age)"
   89  "Pad 2 (warm)"
   90  "Pad 3 (polysynth)"
   91  "Pad 4 (choir)"
   92  "Pad 5 (bowed)"
   93  "Pad 6 (metallic)"
   94  "Pad 7 (halo)"
   95  "Pad 8 (sweep)"
   96  "FX 1 (rain)"
   97  "FX 2 (soundtrack)"
   98  "FX 3 (crystal)"
   99  "FX 4 (atmosphere)"
   100 "FX 5 (brightness)"
   101 "FX 6 (goblins)"
   102 "FX 7 (echoes)"
   103 "FX 8 (sci-fi)"
   104 "Sitar"
   105 "Banjo"
   106 "Shamisen"
   107 "Koto"
   108 "Kalimba"
   109 "Bagpipe"
   110 "Fiddle"
   111 "Shanai"
   112 "Tinkle Bell"
   113 "Agogo"
   114 "Steel Drums"
   115 "Woodblock"
   116 "Taiko Drum"
   117 "Melodic Tom"
   118 "Synth Drum"
   119 "Reverse Cymbal"
   120 "Guitar Fret Noise"
   121 "Breath Noise"
   122 "Seashore"
   123 "Bird Tweet"
   124 "Telephone Ring"
   125 "Helicopter"
   126 "Applause"
   127 "Gunshot"}
  )
